### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by arnau** [daaain/guard-jasmine2JUnit#1]
@daaain Is this still active? archive or destroy?

**Comment by daaain** [comment]
Not active at all since ages, should be archived!

There are a couple more repos I wanted to archive, but not sure what's the process.

**Comment by arnau** [comment]
I'm creating an quarantine list meanwhile we're agreening in a way to archive

**Comment by daaain** [comment]
Resolved this by transferring the ownership of the original repo to my personal account.
